version: '3.7'
services:
  jenkins:
    build: .
    ports:
      - 50000:50000
      - 8080:8080
    environment:
      JENKINS_ADMIN_PASSWORD: none
    volumes:
      - ./casc:/var/jenkins_home/casc
      - ../../:/shakedown
      - ../../examples:/testplan
      - ../../examples:/reports