# -*- coding: utf-8 -*-
# Copyright (c) 2017 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

# Collection of default settings
# override in cofig files or test modules

settings:
  auto_rollback: true
  raise_on_error: true
