version: '3.7'
services:
  jenkins:
    build: jenkins/
#    environment:
#      JAVA_OPTS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
      - ../:/shakedown
      - ../examples:/testplan
      - ../examples/_reports:/reports

  jupyter:
    build: jupyter/
    ports:
      - "8888:8888"
      - "8787:8787"

    volumes:
      - ../:/shakedown
      - ../examples:/notebooks

  
