vars:
    vrf: management
    # upgrade: "flash:EOS-4.20.5F.swi"
    # downgrade: "flash:EOS-4.18.3.1F.swi"

connections:
  veos-1:
    creds: [ admin, "" ]
    protocol: eapi+http
    tags: [ dut, tor ]

  veos-2:
    creds: [ admin,  "" ]
    tags: [ sdut, csp ]


tests:
  basics:
    software_version: 4.20.5F
  ntp:
    servers: ["192.168.56.10"]
  downgrade:
    testrail_case_id: C12345
