vars:
    vrf: management
    upgrade: "flash:EOS-4.19.1F.swi"
    downgrade: "flash:EOS-4.18.3.1F.swi"

connections:
  192.168.56.11:
    creds: [ admin, "" ]
    protocol: eapi+http
    tags: [ dut, tor ]

  192.168.56.12:
    creds: [ admin,  "" ]
    tags: [ sdut, csp ]

tests:
  basics:
    software_version: 4.18.2F
  downgrade:
    testrail_case_id: C12345
