vars:
    vrf: management
    upgrade: "flash:EOS-4.19.1F.swi"
    downgrade: "flash:EOS-4.18.3.1F.swi"

connections:
  veos1:
    creds: [ admin, "" ]
    protocol: eapi+http
    tags: [ dut, tor ]

  veos2:
    creds: [ admin,  "" ]
    tags: [ sdut, csp ]

tests:
  basics:
    software_version: 4.18.2F
  downgrade:
    testrail_case_id: C12345
